# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'imgaKaklPa.ui'
##
## Created by: Qt User Interface Compiler version 6.1.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from __future__ import annotations
import sys
from PyQt5.uic import loadUi
from PyQt5 import QtWidgets
from PyQt5.QtCore import QSize, Qt, QRect, QObject, QCoreApplication, QMetaObject, QPropertyAnimation
from PyQt5.QtWidgets import QApplication, QWidget, QProgressBar, QLabel, QTabWidget, QGridLayout, QVBoxLayout, \
QHBoxLayout, QSizePolicy, QSpacerItem, QStyle, QStyleFactory, QPushButton, QFrame, QFontDialog, QStackedWidget,\
QLineEdit, QTextBrowser, QTextEdit, QPlainTextEdit, QTableWidget, QTableWidgetItem
from PyQt5.QtGui import QImage, QIcon, QPixmap, QPalette, QBrush, QColor, QFontDatabase, QFont, QCursor


class Ui_MainWindow1(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1000, 600)
        MainWindow.setMinimumSize(QSize(1000, 600))
        MainWindow.setMaximumSize(QSize(1000, 600))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setMinimumSize(QSize(1000, 600))
        self.centralwidget.setMaximumSize(QSize(1000, 600))
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(0, 0, 1001, 551))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.stackedWidget = QStackedWidget(self.frame)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(0, 0, 1001, 551))
        self.stackedWidget.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.page_1 = QWidget()
        self.page_1.setObjectName(u"page_1")
        self.frame_3 = QFrame(self.page_1)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(0, 0, 1001, 551))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.label_2 = QLabel(self.frame_3)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(0, 0, 20, 551))
        self.label_2.setStyleSheet(u"background-color: rgb(33, 37, 39);")
        self.label_3 = QLabel(self.frame_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(980, 0, 20, 551))
        self.label_3.setStyleSheet(u"background-color: rgb(33, 37, 39);")
        self.label_4 = QLabel(self.frame_3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(0, -1, 991, 21))
        self.label_4.setStyleSheet(u"background-color: rgb(33, 37, 39);")
        self.label_11 = QLabel(self.frame_3)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 70, 961, 531))
        self.label_11.setPixmap(QPixmap(u"image/1st complete.jpg"))
        self.label_12 = QLabel(self.frame_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(20, 20, 961, 51))
        font = QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet(u"color: rgb(0, 255, 255);\n"
"background-color: rgb(12, 32, 53);\n"
"text-align: center")
        self.label_12.setAlignment(Qt.AlignCenter)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.frame_4 = QFrame(self.page_2)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(0, 0, 1001, 551))
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.label_8 = QLabel(self.frame_4)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(0, 1, 20, 551))
        self.label_8.setStyleSheet(u"background-color: rgb(33, 37, 39);")
        self.label_9 = QLabel(self.frame_4)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(980, 1, 20, 551))
        self.label_9.setStyleSheet(u"background-color: rgb(33, 37, 39);")
        self.label_10 = QLabel(self.frame_4)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(0, 0, 991, 21))
        self.label_10.setStyleSheet(u"background-color: rgb(33, 37, 39);")
        self.label_13 = QLabel(self.frame_4)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(20, 20, 961, 531))
        self.label_13.setPixmap(QPixmap(u"image/2nd complete.jpg"))
        self.label_13.setScaledContents(True)
        self.label_13.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.frame_5 = QFrame(self.page_3)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(0, 0, 1001, 551))
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.label_14 = QLabel(self.frame_5)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(0, 1, 20, 551))
        self.label_14.setStyleSheet(u"background-color: rgb(33, 37, 39);")
        self.label_15 = QLabel(self.frame_5)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(0, 0, 1001, 21))
        self.label_15.setStyleSheet(u"background-color: rgb(33, 37, 39);")
        self.label_25 = QLabel(self.frame_5)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(980, 20, 21, 551))
        self.label_25.setStyleSheet(u"background-color: rgb(33, 37, 39);")
        self.label_24 = QLabel(self.frame_5)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(0, 0, 981, 531))
        self.label_24.setPixmap(QPixmap(u"image/3rd complete.jpg"))
        self.label_24.setScaledContents(True)
        self.label_24.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_25.raise_()
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.frame_6 = QFrame(self.page_4)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(0, 0, 1001, 551))
        self.frame_6.setFrameShape(QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.label_16 = QLabel(self.frame_6)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(0, 10, 20, 551))
        self.label_16.setStyleSheet(u"background-color: rgb(33, 37, 39);")
        self.label_17 = QLabel(self.frame_6)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(0, 0, 1011, 21))
        self.label_17.setStyleSheet(u"background-color: rgb(33, 37, 39);")
        self.label_26 = QLabel(self.frame_6)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(980, 20, 21, 551))
        self.label_26.setStyleSheet(u"background-color: rgb(33, 37, 39);")
        self.label_30 = QLabel(self.frame_6)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(20, 20, 961, 531))
        self.label_30.setPixmap(QPixmap(u"image/weblinker.jpg"))
        self.label_30.setScaledContents(True)
        self.label_32 = QLabel(self.frame_6)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(20, 10, 961, 51))
        self.label_32.setFont(font)
        self.label_32.setStyleSheet(u"color: rgb(0, 255, 255);\n"
"background-color: rgb(12, 32, 53);\n"
"text-align: center")
        self.label_32.setAlignment(Qt.AlignCenter)
        self.label_30.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_26.raise_()
        self.label_32.raise_()
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QWidget()
        self.page_5.setObjectName(u"page_5")
        self.frame_7 = QFrame(self.page_5)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(0, 0, 1011, 551))
        self.frame_7.setFrameShape(QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Raised)
        self.label_18 = QLabel(self.frame_7)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(0, 1, 20, 551))
        self.label_18.setStyleSheet(u"background-color: rgb(33, 37, 39);")
        self.label_19 = QLabel(self.frame_7)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(0, 0, 991, 21))
        self.label_19.setStyleSheet(u"background-color: rgb(33, 37, 39);")
        self.label_27 = QLabel(self.frame_7)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(980, 10, 21, 551))
        self.label_27.setStyleSheet(u"background-color: rgb(33, 37, 39);")
        self.label_33 = QLabel(self.frame_7)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(20, 20, 961, 531))
        self.label_33.setPixmap(QPixmap(u"image/timetable manager.jpg"))
        self.label_33.setScaledContents(True)
        self.label_33.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_27.raise_()
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QWidget()
        self.page_6.setObjectName(u"page_6")
        self.frame_8 = QFrame(self.page_6)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setGeometry(QRect(0, 0, 1001, 551))
        self.frame_8.setFrameShape(QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Raised)
        self.label_20 = QLabel(self.frame_8)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(0, 1, 20, 551))
        self.label_20.setStyleSheet(u"background-color: rgb(33, 37, 39);")
        self.label_21 = QLabel(self.frame_8)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(0, 0, 1001, 31))
        self.label_21.setStyleSheet(u"background-color: rgb(33, 37, 39);")
        self.label_28 = QLabel(self.frame_8)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(980, 20, 21, 551))
        self.label_28.setStyleSheet(u"background-color: rgb(33, 37, 39);")
        self.label_31 = QLabel(self.frame_8)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(20, 20, 961, 531))
        self.label_31.setPixmap(QPixmap(u"image/lecname understading....jpg"))
        self.label_31.setScaledContents(True)
        self.label_31.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_28.raise_()
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QWidget()
        self.page_7.setObjectName(u"page_7")
        self.frame_9 = QFrame(self.page_7)
        self.frame_9.setObjectName(u"frame_9")
        self.frame_9.setGeometry(QRect(0, 0, 1001, 551))
        self.frame_9.setFrameShape(QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QFrame.Raised)
        self.label_22 = QLabel(self.frame_9)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(0, 1, 20, 551))
        self.label_22.setStyleSheet(u"background-color: rgb(33, 37, 39);")
        self.label_23 = QLabel(self.frame_9)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(0, 0, 1001, 21))
        self.label_23.setStyleSheet(u"background-color: rgb(33, 37, 39);")
        self.label_29 = QLabel(self.frame_9)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(980, 20, 21, 551))
        self.label_29.setStyleSheet(u"background-color: rgb(33, 37, 39);")
        self.label_35 = QLabel(self.frame_9)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(20, 20, 961, 531))
        self.label_35.setPixmap(QPixmap(u"image/antaryamimi.jpg"))
        self.label_35.setScaledContents(True)
        self.label_35.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_29.raise_()
        self.stackedWidget.addWidget(self.page_7)
        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(0, 549, 1001, 51))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.label = QLabel(self.frame_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(-2, 5, 1001, 51))
        self.label.setStyleSheet(u"background-color: rgb(33, 37, 39);")
        self.next = QPushButton(self.frame_2)
        self.next.setObjectName(u"next")
        self.next.setGeometry(QRect(660, 20, 221, 24))
        self.next.setStyleSheet(u"\n"
"QPushButton {\n"
"	color: rgb(255, 255, 255);\n"
"	border: 2px solid rgb(0, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(103, 255, 2);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(224, 0, 0);\n"
"    border-style: inset;\n"
"}\n"
"")
        self.prev = QPushButton(self.frame_2)
        self.prev.setObjectName(u"prev")
        self.prev.setGeometry(QRect(140, 20, 221, 24))
        self.prev.setStyleSheet(u"\n"
"QPushButton {\n"
"	color: rgb(255, 255, 255);\n"
"	border: 2px solid rgb(0, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(103, 255, 2);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(224, 0, 0);\n"
"    border-style: inset;\n"
"}\n"
"")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label_2.setText("")
        self.label_3.setText("")
        self.label_4.setText("")
        self.label_11.setText("")
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"FOR AUTOMATION IT'S NEEDED.", None))
        self.label_8.setText("")
        self.label_9.setText("")
        self.label_10.setText("")
        self.label_13.setText("")
        self.label_14.setText("")
        self.label_15.setText("")
        self.label_25.setText("")
        self.label_24.setText("")
        self.label_16.setText("")
        self.label_17.setText("")
        self.label_26.setText("")
        self.label_30.setText("")
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"HOW IT WORKES..", None))
        self.label_18.setText("")
        self.label_19.setText("")
        self.label_27.setText("")
        self.label_33.setText("")
        self.label_20.setText("")
        self.label_21.setText("")
        self.label_28.setText("")
        self.label_31.setText("")
        self.label_22.setText("")
        self.label_23.setText("")
        self.label_29.setText("")
        self.label_35.setText("")
        self.label.setText("")
        self.next.setText(QCoreApplication.translate("MainWindow", u"NEXT", None))
        self.prev.setText(QCoreApplication.translate("MainWindow", u"PREVIOUS", None))
    # retranslateUi

